# Site settings
title: Archene's Jekyll Blog
email: ray.mcmahan1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing Jekyll on Github Pages arxene.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "archene.com" # the base hostname & protocol for your site
github_username:  arxene

# Build settings
markdown: kramdown
highlighter: pygments